os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3

before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew tap vapor/tap;
      brew update;
      brew install ctls;
    fi

script:
  - eval "$(curl -sL https://swift.vapor.sh/ci-3.1)"

after_success:
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
