version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL}

services:
  {{name}}:
    image: {{name}}:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    {{#fluent}}depends_on:
      - db{{/fluent}}
    ports:
      - '8080:80'

  {{#fluent}}migrator:
    image: {{name}}:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    command:
      - 'migrate'
    stdin_open: true
    tty: true
    deploy:
      replicas: 0 # use `docker service scale` to spin up.{{/fluent}}

  {{#fluent.db.is_postgres}}db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'{{/fluent.db.is_postgres}}{{#fluent.db.is_mysql}}
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
      MYSQL_DATABASE: vapor_database
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'{{/fluent.db.is_mysql}}

##
## Building
##
## - `docker-compose build`
##
## https://docs.docker.com/compose/reference/build/

##
## Running Containers
##
## - `docker-compose up` to run all services.
##
## https://docs.docker.com/compose/reference/up/

##
## Running Services in Swarm (local or remote)
##
## - `docker swarm init` (run once)
## - `docker stack deploy -c docker-compose.yml <stack-name>` to deploy a stack with whatever name you want.
## - `docker service ls` to see running services.
## - `docker service logs -f <service-name>` to tail logs for a service.
## - `docker stack rm <stack-name>` to bring the stack down.
##
## https://docs.docker.com/engine/swarm/stack-deploy/
